// Tropes.js

const subGenres = {
    "Action Adventure": [
        "Ancient Secrets",
        "Black-and-White Morality",
        "Double-Cross",
        "Exotic Locations",
        "High Action",
        "Larger-Than-Life Threat",
        "Linear Plotlines",
        "MacGuffin",
        "Military Exploits",
        "Puzzle Solving",
        "The Love Interest",
        "Unbreakable Codes"
    ],
    "Character": [
        "All Grown Up",
        "Antihero",
        "Barbarian",
        "Best Friend's Ex",
        "Billionaire",
        "Chosen One",
        "Dark Lord",
        "Emotional Scars",
        "Femme Fatale",
        "Heroic Seductress",
        "Men in Uniform",
        "Orphan",
        "Outsider",
        "Physically Different",
        "Playboy",
        "Politician",
        "Priest",
        "Rejected as Unworthy",
        "Reluctant Hero",
        "Royal",
        "The Waiting Evil",
        "Ugly Duckling",
        "Vamp",
        "Virgin/Surprise Virgin",
        "Wallflower",
        "Widow",
        "Woman Scorned"
    ],
    "Children's": [
        "Appreciating Our Differences",
        "Bravery",
        "Compassion",
        "Courage",
        "Dedication",
        "Dealing With Adversity",
        "Dealing With Anger",
        "Defective Animal",
        "Going to School",
        "Growing Up",
        "Honesty",
        "Learning About Family",
        "Learning a New Skill",
        "Learning to Share",
        "Loyalty",
        "Power of Friendship",
        "Power of Imagination",
        "Power of Teamwork",
        "Talking Animals"
    ],
    "Contemporary": [
        "Coming of Age",
        "Conflict Comes from Interpersonal Relationships",
        "Dealing with Mental Illness, Addiction, Sexual Orientation, and/or Abuse",
        "Family Drama",
        "Lack of Common Plot Structure",
        "No Otherworldly Elements",
        "Set in the Modern Day",
        "Unresolved Endings Are Common"
    ],
    "Fantasy": [
        "Best of the Best",
        "Epic Storylines",
        "Heir to the Throne",
        "High Stakes",
        "Magical Creatures",
        "Medieval-Adjacent Setting",
        "Powerful Artifacts",
        "Rescued by the Cavalry",
        "Side Quests",
        "The Chosen One",
        "The Damsel in Distress",
        "The Evil One",
        "The Mentor",
        "The Reluctant Hero",
        "The Training Sequence",
        "Unlikely Allies"
    ],
    "General": [],
    "Historical Fiction": [
        "Colonial America",
        "Colonization",
        "Combining Real and Fictional Events",
        "Dual Timeline",
        "Historical Figures",
        "Korean War",
        "Multiple Timelines",
        "Pre-Colonization",
        "Religious Themes",
        "Social and Political Turmoil",
        "Traveling Long Distances",
        "Vietnam War",
        "WWI",
        "WWII"
    ],
    "Horror": [
        "Backing Into Darkness",
        "Bad Things Happen at Night",
        "Creepy Settings",
        "Cults and Religious Extremists",
        "Cursed Items",
        "Deal With the Devil",
        "Easily Definable Characters",
        "Glowing Eyes",
        "Humans Can Be Evil",
        "Karmic Retribution",
        "Losing the Ability to Run",
        "Monsters",
        "Mysterious Things Happening",
        "Paralyzed With Fear",
        "Severed Limbs",
        "The Antichrist",
        "The Unhappy Ending",
        "The World is Ending",
        "Traumatic Past"
    ],
    "Mystery": [
        "Amnesia",
        "Close Quarters",
        "Consulting a Criminal",
        "Detective with a Haunted Past",
        "Outsmarting the Criminal",
        "Protagonist is a Suspect",
        "Red Herring",
        "Righting Past Wrongs",
        "The Alibi",
        "The Dramatic Reveal",
        "The Trophy",
        "Unlikable Victim"
    ],
    "Plot": [
        "Alien Pregnancy",
        "All Powerful Artifacts",
        "Amnesia",
        "Ancient Secrets",
        "An Inheritance",
        "Arranged Marriage",
        "Belated Love Epiphany",
        "Betrayal",
        "Blackmail",
        "Blind Date",
        "Break Up to Save Them",
        "Can't Spit it Out",
        "Changing Sexual Preference",
        "Conjuring Evil",
        "Countdown to Destruction",
        "Damsel in Distress",
        "Dark Secret",
        "Disguise",
        "Dragons",
        "Everyone Can See It",
        "Fairytale Retelling",
        "Fake Relationship",
        "First Contact",
        "Fish Out of Water",
        "Forced Marriage",
        "Gone Horribly Right",
        "Good vs Evil",
        "Innocent Cohabitation",
        "Jilted Bride",
        "Kidnapped",
        "Last to Know",
        "Long Distance Relationship",
        "Love Potion",
        "Love Triangle",
        "Love at First Sight",
        "Luck Novice",
        "Magic",
        "Magic School",
        "Mistaken Declaration of Love",
        "Mistaken Identity",
        "Nobody Thinks It Will Work",
        "Not Good Enough for Them",
        "Oblivious to Love",
        "Oppressed Robots",
        "Overqualified Party",
        "Parallel Worlds",
        "Powerful Artifact",
        "Redemption",
        "Revenge",
        "Road Trip",
        "Runaway Bride",
        "Secret Admirer",
        "Secret Baby",
        "Secret/Lost Heir",
        "Surprise Pregnancy",
        "The 'Here Comes the Cavalry' Twist",
        "The Bad Guy Won't Die",
        "There's Only One Bed",
        "Time Travel",
        "Training Sequence",
        "Trapped in an Elevator",
        "War",
        "Working with the Ex",
        "You’ve Changed"
    ],
    "Relationships": [
        "Afraid to Commit",
        "Age Gap",
        "Beauty and the Beast",
        "Best Friend's Lover / Sibling",
        "Bodyguard/Protector",
        "Bully Turned Nice Guy",
        "Enemies-to-Lovers",
        "Fling",
        "Forbidden Love",
        "Found Family",
        "Friends-to-Lovers",
        "If I Can't Have You, Nobody Will",
        "In Love with the Best Man",
        "Incapable of Love",
        "Interspecies Romance",
        "Literal Man Eater",
        "Love Interest Has Profession Protagonist Hates",
        "Love Interest Reminds of Estranged Family Member",
        "Love Is the Answer",
        "Love Triangle",
        "Love/Hate Relationship",
        "Loveable Rogue",
        "Lovers in Denial",
        "Mafia",
        "Marriage Before Romance",
        "Marriage of Convenience",
        "Matchmaker Gone Wrong",
        "Oblivious to Love",
        "Office Romance",
        "Old Enemies",
        "Opposites Attract",
        "Parent with Child's Caregiver / New Love",
        "Pen Pals to Lovers",
        "Put Them All Out of My Misery",
        "Reunion Romance",
        "Rich vs. Poor",
        "Rivals",
        "Second Chance Romance",
        "Sibling's Ex / Lovers-to-Siblings",
        "Sleeps with Everyone But You",
        "Socially Inferior / Superior",
        "Soulmate",
        "Sporty Love Interest",
        "Star-Crossed Lovers",
        "Step Siblings",
        "Strangers-to-Lovers",
        "Sunny vs. Grumpy",
        "Sworn Off a Relationship",
        "The One That Got Away",
        "Unattainable Love Interest",
        "Undercover Lover",
        "Unrequited Love"
    ],
    "Romantic": [
        "Enemies to Lovers",
        "Fated Mates",
        "Fake Relationship",
        "First Love",
        "Forbidden Love",
        "Forced Proximity",
        "Fling",
        "Happy Ending",
        "Incapable of Love",
        "Love Is the Answer",
        "Love Triangle",
        "Love at First Glimpse",
        "Marriage of Convenience",
        "The Other Woman/Man",
        "Unexpected Love Interest"
    ],
    "Science Fiction": [
        "Aliens",
        "Alternate Dimensions/Universes",
        "Army of Clones",
        "Artificial Intelligence",
        "Body Switching",
        "Destroying the Universe",
        "Downloading People",
        "Dystopian",
        "End of Human Race",
        "Implants",
        "Nanotech",
        "Power and Technology",
        "Space Travel",
        "Time Travel"
    ],
    "Setting": [
        "Africa",
        "Aliens Built Earth",
        "Alone in a Dark House",
        "Antarctica",
        "Asia",
        "Australia",
        "Europe",
        "Indigenous Peoples",
        "North America",
        "Pseudo Medieval Europe Setting",
        "South America"
    ],
    "Thriller/Suspense": [
        "Cliffhanger",
        "Exotic Locales",
        "Gaslighting",
        "High Stakes",
        "Insurmountable Odds",
        "Missing Children or Spouses",
        "The Frame-Up",
        "The Stalker",
        "Ticking Clock",
        "Troubled Protagonist",
        "Twist Ending",
        "Unreliable Narrator"
    ],
    "Young Adult": [
        "Dark Family Secret",
        "Discovering Special Powers",
        "Useless or Evil Adults"
    ]
};

module.exports = subGenres;
