const PubTree = {
    0: [ // broad_genre 
        { text: 'Fiction', next: 'category', id: 1, broad_genre: 'fiction' },
        { text: 'Non-Fiction', next: 'category', id: 2, broad_genre: 'non-fiction' }
    ],
    1: [ // category
        { text: 'Novel', next: 2, id: 3, category: 'novel' },
        { text: 'Novella', next: 2, id: 4, category: 'novella' },
        { text: 'Short Story Collection', next: 2, id: 5, category: 'short story collection' },
        { text: 'Graphic Novel', next: 2, id: 7, category: 'graphic novel'  },
        { text: 'Novel in Verse', next: 2, id: 8, category: 'novel in verse'  },
        { text: 'Poetry Collection', next: 2, id: 9, category: 'poetry collection' },
        { text: 'Chapter Book', id: 10, category: 'chapter book' },
        { text: 'Picture Book', next: 8, id: 6, category: 'picture book' },
        { text: 'Early Reader', id: 11, category: 'early reader' },
        // { text: 'Novel', next: '2', id: 3, category: 'novel' },
        // { text: 'Novella', next: '2', id: 4, category: 'novella' },
        // { text: 'Short Story Collection', next: '2', id: 5, category: 'short story collection' },
        // { text: 'Graphic Novel', next: 'age_group', id: 7, category: 'graphic novel' },
        // { text: 'Novel in Verse', next: 'age_group', id: 8, category: 'novel in verse' },
        // { text: 'Poetry Collection', next: 'age_group', id: 9, category: 'poetry collection' },
        // { text: 'Chapter Book', id: 10, category: 'chapter book' },
        // { text: 'Early Reader', id: 11, category: 'early reader' }
    ],
    2: [ // age_group
        { text: 'Adult', next: 3, id: 12, age_group: 'adult' },
        { text: 'New Adult', next: 4, id: 13, age_group: 'new_adult' },
        { text: 'Young Adult', next: 4, id: 14, age_group: 'young_adult' },
        { text: 'Middle Grade', next: 5, id: 15, age_group: 'middle_grade' },
    ],
    3: [ // genre
        { text: 'Action/Adventure', id: 16, genre: 'action/adventure' },
        { text: 'Book Club', id: 17, genre: 'book club' },
        { text: 'Chick Lit', id: 18, genre: 'chick lit' },
        { text: 'Commercial', id: 19, genre: 'commercial' }, 
        { text: 'Contemporary', id: 20, genre: 'contemporary' },
        { text: 'Crime/Police', id: 21, genre: 'crime/police' },
        { text: 'Erotica', id: 22, genre: 'erotica' },
        { text: 'Family Saga', id: 23, genre: 'family saga' },
        { text: 'Fantasy', next: 6, id: 24, genre: 'fantasy' },
        { text: 'General Fiction', id: 25, genre: 'general fiction' },
        { text: 'Gothic', id: 26, genre: 'gothic' },
        { text: 'Historical', id: 27, genre: 'historical' },
        { text: 'Horror', id: 28, genre: 'horror' },
        { text: 'Humor/Satire', id: 29, genre: 'humor/satire' },
        { text: 'LGBTQ+', id: 30, genre: 'lgbtq+' },
        { text: 'Literary Fiction', id: 31, genre: 'literary fiction' },
        { text: 'Military/Espionage', id: 32, genre: 'military/espionage' },
        { text: 'Multicultural', id: 33, genre: 'multicultural' },
        { text: 'Mystery', next: 7, id: 34, genre: 'mystery' },
        { text: 'Offbeat/Quirky', id: 35, genre: 'offbeat/quirky' },
        { text: 'Romance', next: 9, id: 36, genre: 'romance' },
        { text: 'Religious/Inspirational', id: 37, genre: 'religious/inspirational' },
        { text: 'Science Fiction', id: 38, genre: 'science fiction' },
        { text: 'Speculative', id: 39, genre: 'speculative' },
        { text: 'Thrillers/Suspense', id: 40, genre: 'thrillers/suspense' },
        { text: 'Upmarket', id: 41, genre: 'upmarket' },
        { text: 'Western', id: 42, genre: 'western' },
        { text: 'Women\'s Fiction', id: 43, genre: 'women\'s fiction' },
    ],
    4: [ // genre
        { text: 'Christian', id: 44, genre: 'christian' },
        { text: 'Contemporary', id: 20, genre: 'contemporary' },
        { text: 'Fantasy', next: 6, id: 24, genre: 'fantasy' },
        { text: 'Historical', id: 27, genre: 'historical' },
        { text: 'Horror', id: 28, genre: 'horror' },
        { text: 'Humor', id: 45, genre: 'humor' },
        { text: 'LGBTQ+', id: 30, genre: 'lgbtq+' },
        { text: 'Literary', id: 46, genre: 'literary' },
        { text: 'Mystery', next: 7, id: 34, genre: 'mystery' },
        { text: 'Paranormal', id: 47, genre: 'paranormal' },
        { text: 'Paranormal Romance', id: 48, genre: 'paranormal romance' },
        { text: 'Romance', next: 9, id: 36, genre: 'romance' },
        { text: 'Science Fiction', id: 38, genre: 'science fiction' },
        { text: 'Speculative', id: 39, genre: 'speculative' },
        { text: 'Thriller/Suspense', id: 49, genre: 'thriller/suspense' },
    ],
    5: [ // genre
        { text: 'Adventure', id: 50, genre: 'adventure' },
        { text: 'Christian', id: 44, genre: 'christian' },
        { text: 'Contemporary', id: 20, genre: 'contemporary' },
        { text: 'Fantasy', next: 6, id: 24, genre: 'fantasy' },
        { text: 'Historical', id: 27, genre: 'historical' },
        { text: 'Horror', id: 28, genre: 'horror' },
        { text: 'Humor', id: 45, genre: 'humor' },
        { text: 'Literary', id: 46, genre: 'literary' },
        { text: 'Mystery', next: 7, id: 34, genre: 'mystery' },
        { text: 'Science Fiction', id: 38, genre: 'science fiction' },
    ],
    6: [ // genre
        { text: 'Contemporary/Urban Fantasy', id: 51, genre: 'contemporary/urban fantasy' },
        { text: 'Dark Fantasy', id: 52, genre: 'dark fantasy' },
        { text: 'High/Epic Fantasy', id: 53, genre: 'high/epic fantasy' },
        { text: 'Historical Fantasy', id: 54, genre: 'historical fantasy' },
        { text: 'Magical Realism', id: 55, genre: 'magical realism' },
        { text: 'Paranormal Fantasy', id: 56, genre: 'paranormal fantasy' },
        { text: 'Steampunk Fantasy', id: 57, genre: 'steampunk fantasy' },
    ],
    7: [ // genre
        { text: 'Cozy', id: 58, genre: 'cozy' },
        { text: 'Historical', id: 27, genre: 'historical' },       
    ],
    8: [// genre
        { text: 'Picture Book', id: 6, genre: 'picture book' },
        { text: 'Author', id: 59, genre: 'author' },
        { text: 'Author/Illustrator', id: 60, genre: 'author/illustrator' },
        { text: 'Illustrator', id: 61, genre: 'illustrator' },
    ],
    9: [ // genre
        { text: 'Amish Romance', id: 62, genre: 'amish romance' },
        { text: 'Romantic Comedy', id: 63, genre: 'romantic comedy' },   
        { text: 'Contemporary Romance', id: 64, genre: 'contemporary romance' },
        { text: 'Fantasy Romance', id: 65, genre: 'fantasy romance' },
        { text: 'Gothic Romance', id: 66, genre: 'gothic romance' },
        { text: 'Historical Romance', id: 67, genre: 'historical romance' },
        { text: 'Inspirational Romance', id: 68, genre: 'inspirational romance' },
        { text: 'LGBTQ+ Romance', id: 69, genre: 'lgbtq+ romance' },
        { text: 'Multicultural Romance', id: 70, genre: 'multicultural romance' },
        { text: 'Paranormal Romance', id: 47, genre: 'paranormal romance' },
        { text: 'Regency Romance', id: 71, genre: 'regency romance' },
        { text: 'Southern Romance', id: 72, genre: 'southern romance' },
        { text: 'Sweet Romance', id: 73, genre: 'sweet romance' },       
        { text: 'Romantic Suspense', id: 74, genre: 'romantic suspense' },  
        { text: 'Western Romance', id: 75, genre: 'western romance' },
    ],
    10: [ //genre
        { text: 'Arts & Entertainment', next: 11, id: 76, category: 'arts & entertainment' },
        { text: 'Biography & Memoir', next: 12, id: 77, category: 'biography & memoir' },
        { text: 'Business & Finance', id: 78, category: 'business & finance' },
        { text: 'Food & Lifestyle', next: 13, id: 79, category: 'food & lifestyle' },
        { text: 'Home & Garden', next: 14, id: 80, category: 'home & garden' },
        { text: 'Current Events & Social Issues', next: 15, id: 81, category: 'current events & social issues' },
        { text: 'Health & Wellness', next: 16, id: 82, category: 'health & wellness' },
        { text: 'History & Military', next: 17, id: 83, category: 'history & military' },
        { text: 'Hobbies & Interests', next: 18, id: 84, category: 'hobbies & interests' },
        { text: 'Reference & Education', next: 19, id: 85, category: 'reference & education' },
        { text: 'Relationships & Personal Growth', next: 20, id: 86, category: 'relationships & personal growth' },
        { text: 'Religion & Spirituality', id: 87, category: 'religion & spirituality' },
        { text: 'Science & Technology', id: 88, category: 'science & technology' },
        { text: 'Social Sciences', next: 21, id: 89, category: 'social sciences' },
        { text: 'True Crime & Adventure', id: 90, category: 'true crime & adventure' },
    ],
    11: [
        { text: 'Arts & Entertainment General', id: 91, genre: 'arts & entertainment general' },
        { text: 'Art/Photography', id: 92, genre: 'art/photography' },
    ],
    12: [
        { text: 'Biography', id: 93, genre: 'biography' },
        { text: 'Memoir', id: 94, genre: 'memoir' },
    ],
    13: [
        { text: 'Cookbook', id: 95, genre: 'cookbook' },
        { text: 'Food/Lifestyle', id: 96, genre: 'food/lifestyle' },
    ],
    14: [
        { text: 'Decorating/Design', id: 97, genre: 'decorating/design' },
        { text: 'Gardening', id: 98, genre: 'gardening' },
    ],
    15: [
        { text: 'Cultural/Social Issues', id: 99, genre: 'cultural/social issues' },
        { text: 'Current Affairs/Politics', id: 100, genre: 'current affairs/politics' },
    ],
    16: [
        { text: 'Health/Fitness', id: 101, genre: 'health/fitness' },
        { text: 'Psychology', id: 102, genre: 'psychology' },
    ],
    17: [
        { text: 'History', id: 103, genre: 'history' },
        { text: 'Military', id: 104, genre: 'military' },
    ],
    18: [
        { text: 'How To', id: 105, genre: 'how to' },
        { text: 'Humor/Gift Book', id: 106, genre: 'humor/gift book' },
        { text: 'Pop Culture', id: 107, genre: 'pop culture' },
        { text: 'Pets', id: 108, genre: 'pets' },
        { text: 'Sports', id: 109, genre: 'sports' },
        { text: 'Travel', id: 110, genre: 'travel' },
    ],
    19: [
        { text: 'General Non-Fiction', id: 111, genre: 'general non-fiction' },
        { text: 'Juvenile/Graphic', id: 112, genre: 'juvenile/graphic' },
        { text: 'Reference', id: 113, genre: 'reference' },
    ],
    20: [
        { text: 'Relationship/Dating', id: 114, genre: 'relationship/dating' },
        { text: 'Self-Help', id: 115, genre: 'self-help' },
    ],
    21: [
        { text: 'LGBTQ+', id: 30, genre: 'lgbtq+' },
        { text: 'Multicultural', id: 33, genre: 'multicultural' },
        { text: 'Nature/Ecology', id: 116, genre: 'nature/ecology' },
        { text: 'Parenting', id: 117, genre: 'parenting' },
        { text: 'Women\'s Issues', id: 118, genre: 'women\'s issues' },
    ],

};

export default PubTree;


// const PubTree = {
//     0: [ // broad_genre 
//         { text: 'Fiction', next: 1, id: 1 },
//         { text: 'Non-Fiction', next: 10, id: 2 }
//     ],
//     1: [ // category
//         { text: 'Novel', next: 2, id: 3 },
//         { text: 'Novella', next: 2, id: 4 },
//         { text: 'Short Story Collection', next: 2, id: 5 },
//         { text: 'Picture Book', next: 8, id: 6 },
//         { text: 'Graphic Novel', next: 2, id: 7 },
//         { text: 'Novel in Verse', next: 2, id: 8 },
//         { text: 'Poetry Collection', next: 2, id: 9 },
//         { text: 'Chapter Book', id: 10 },
//         { text: 'Early Reader', id: 11 },
//     ],
//     2: [ // age_group
//         { text: 'Adult', next: 3, id: 12 },
//         { text: 'New Adult', next: 4, id: 13 },
//         { text: 'Young Adult', next: 4, id: 14 },
//         { text: 'Middle Grade', next: 5, id: 15 },
//     ],
//     3: [ // genre
//         { text: 'Action/Adventure', id: 16 },
//         { text: 'Book Club', id: 17 },
//         { text: 'Chick Lit', id: 18 },
//         { text: 'Commercial', id: 19 }, 
//         { text: 'Contemporary', id: 20 },
//         { text: 'Crime/Police', id: 21 },
//         { text: 'Erotica', id: 22 },
//         { text: 'Family Saga', id: 23 },
//         { text: 'Fantasy', next: 6, id: 24 },
//         { text: 'General Fiction', id: 25 },
//         { text: 'Gothic', id: 26 },
//         { text: 'Historical', id: 27 },
//         { text: 'Horror', id: 28 },
//         { text: 'Humor/Satire', id: 29 },
//         { text: 'LGBTQ+', id: 30 },
//         { text: 'Literary Fiction', id: 31 },
//         { text: 'Military/Espionage', id: 32 },
//         { text: 'Multicultural', id: 33 },
//         { text: 'Mystery', next: 7, id: 34 },
//         { text: 'Offbeat/Quirky', id: 35 },
//         { text: 'Romance', next: 9, id: 36 },
//         { text: 'Religious/Inspirational', id: 37 },
//         { text: 'Science Fiction', id: 38 },
//         { text: 'Speculative', id: 39 },
//         { text: 'Thrillers/Suspense', id: 40 },
//         { text: 'Upmarket', id: 41 },
//         { text: 'Western', id: 42 },
//         { text: 'Women\'s Fiction', id: 43 },
//     ],
//     4: [ // genre
//         { text: 'Christian', id: 44 },
//         { text: 'Contemporary', id: 20 },
//         { text: 'Fantasy', next: 6, id: 24 },
//         { text: 'Historical', id: 27 },
//         { text: 'Horror', id: 28 },
//         { text: 'Humor', id: 45 },
//         { text: 'LGBTQ+', id: 30 },
//         { text: 'Literary', id: 46 },
//         { text: 'Mystery', next: 7, id: 34 },
//         { text: 'Paranormal', id: 47 },
//         { text: 'Paranormal Romance', id: 48 },
//         { text: 'Romance', next: 9, id: 36 },
//         { text: 'Science Fiction', id: 38 },
//         { text: 'Speculative', id: 39 },
//         { text: 'Thriller/Suspense', id: 49 },
//     ],
//     5: [ // genre
//         { text: 'Adventure', id: 50 },
//         { text: 'Christian', id: 44 },
//         { text: 'Contemporary', id: 20 },
//         { text: 'Fantasy', next: 6, id: 24 },
//         { text: 'Historical', id: 27 },
//         { text: 'Horror', id: 28 },
//         { text: 'Humor', id: 45 },
//         { text: 'Literary', id: 46 },
//         { text: 'Mystery', next: 7, id: 34 },
//         { text: 'Science Fiction', id: 38 },
//     ],
//     6: [ // genre
//         { text: 'Contemporary/Urban Fantasy', id: 51 },
//         { text: 'Dark Fantasy', id: 52 },
//         { text: 'High/Epic Fantasy', id: 53 },
//         { text: 'Historical Fantasy', id: 54 },
//         { text: 'Magical Realism', id: 55 },
//         { text: 'Paranormal Fantasy', id: 56 },
//         { text: 'Steampunk Fantasy', id: 57 },
//     ],
//     7: [ // genre
//         { text: 'Cozy', id: 58 },
//         { text: 'Historical', id: 27 },       
//     ],
//     8: [// genre
//         { text: 'Picture Book', id: 6 },
//         { text: 'Author', id: 59 },
//         { text: 'Author/Illustrator', id: 60 },
//         { text: 'Illustrator', id: 61 },
//     ],
//     9: [ // genre
//         { text: 'Amish Romance', id: 62 },
//         { text: 'Romantic Comedy', id: 63 },   
//         { text: 'Contemporary Romance', id: 64 },
//         { text: 'Fantasy Romance', id: 65 },
//         { text: 'Gothic Romance', id: 66 },
//         { text: 'Historical Romance', id: 67 },
//         { text: 'Inspirational Romance', id: 68 },
//         { text: 'LGBTQ+ Romance', id: 69 },
//         { text: 'Multicultural Romance', id: 70 },
//         { text: 'Paranormal Romance', id: 47 },
//         { text: 'Regency Romance', id: 71 },
//         { text: 'Southern Romance', id: 72 },
//         { text: 'Sweet Romance', id: 73 },       
//         { text: 'Romantic Suspense', id: 74 },  
//         { text: 'Western Romance', id: 75 },
//     ],
//     10: [ //genre
//         { text: 'Arts & Entertainment', next: 11, id: 76 },
//         { text: 'Biography & Memoir', next: 12, id: 77 },
//         { text: 'Business & Finance', id: 78 },
//         { text: 'Food & Lifestyle', next: 13, id: 79 },
//         { text: 'Home & Garden', next: 14, id: 80 },
//         { text: 'Current Events & Social Issues', next: 15, id: 81 },
//         { text: 'Health & Wellness', next: 16, id: 82 },
//         { text: 'History & Military', next: 17, id: 83 },
//         { text: 'Hobbies & Interests', next: 18, id: 84 },
//         { text: 'Reference & Education', next: 19, id: 85 },
//         { text: 'Relationships & Personal Growth', next: 20, id: 86 },
//         { text: 'Religion & Spirituality', id: 87 },
//         { text: 'Science & Technology', id: 88 },
//         { text: 'Social Sciences', next: 21, id: 89 },
//         { text: 'True Crime & Adventure', id: 90 },
//     ],
//     11: [
//         { text: 'Arts & Entertainment General', id: 91 },
//         { text: 'Art/Photography', id: 92 },
//     ],
//     12: [
//         { text: 'Biography', id: 93 },
//         { text: 'Memoir', id: 94 },
//     ],
//     13: [
//         { text: 'Cookbook', id: 95 },
//         { text: 'Food/Lifestyle', id: 96 },
//     ],
//     14: [
//         { text: 'Decorating/Design', id: 97 },
//         { text: 'Gardening', id: 98 },
//     ],
//     15: [
//         { text: 'Cultural/Social Issues', id: 99 },
//         { text: 'Current Affairs/Politics', id: 100 },
//     ],
//     16: [
//         { text: 'Health/Fitness', id: 101 },
//         { text: 'Psychology', id: 102 },
//     ],
//     17: [    
//         { text: 'History', id: 103 },
//         { text: 'Military', id: 104 },
//     ],
//     18: [
//         { text: 'How To', id: 105 },
//         { text: 'Humor/Gift Book', id: 106 },
//         { text: 'Pop Culture', id: 107 },
//         { text: 'Pets', id: 108 },
//         { text: 'Sports', id: 109 },
//         { text: 'Travel', id: 110 },
//     ],
//     19: [ 
//         { text: 'General Non-Fiction', id: 111 },
//         { text: 'Juvenile/Graphic', id: 112 },
//         { text: 'Reference', id: 113 },
//     ],
//     20: [
//         { text: 'Relationship/Dating', id: 114 },
//         { text: 'Self-Help', id: 115 },
//     ],
//     21: [
//         { text: 'LGBTQ+', id: 30 },
//         { text: 'Multicultural', id: 33 },
//         { text: 'Nature/Ecology', id: 116 },
//         { text: 'Parenting', id: 117 },
//         { text: 'Women\'s Issues', id: 118 },
//     ],
// };

// export default PubTree;



// const PubTree = {
//     0: [ // genre 
//         { text: 'Fiction', next: 1, id: 1 },
//         { text: 'Non-Fiction', next: 10, id: 2 }
//     ],
//     1: [ // fiction categories  
//         { text: 'Novel', next: 2, id: 3 },
//         { text: 'Novella', next: 2, id: 4 },
//         { text: 'Short Story Collection', next: 2, id: 5 },
//         { text: 'Picture Book', next: 8, id: 6 },
//         { text: 'Graphic Novel', next: 2, id: 7 },
//         { text: 'Novel in Verse', next: 2, id: 8 },
//         { text: 'Poetry Collection', next: 2, id: 9 },
//         { text: 'Chapter Book', id: 10 },
//         { text: 'Early Reader', id: 11 },
//     ],
//     2: [ // fiction ages  
//         { text: 'Adult', next: 3, id: 12 },
//         { text: 'New Adult', next: 4, id: 13 },
//         { text: 'Young Adult', next: 4, id: 14 },
//         { text: 'Middle Grade', next: 5, id: 15 },
//     ],
//     3: [ // adult genres
//         { text: 'Action/Adventure', id: 16 },
//         { text: 'Book Club', id: 17 },
//         { text: 'Chick Lit', id: 18 },
//         { text: 'Commercial', id: 19 }, 
//         { text: 'Contemporary', id: 20 },
//         { text: 'Crime/Police', id: 21 },
//         { text: 'Erotica', id: 22 },
//         { text: 'Family Saga', id: 23 },
//         { text: 'Fantasy', next: 6, id: 24 },
//         { text: 'General Fiction', id: 25 },
//         { text: 'Gothic', id: 26 },
//         { text: 'Historical', id: 27 },
//         { text: 'Horror', id: 28 },
//         { text: 'Humor/Satire', id: 29 },
//         { text: 'LGBTQ+', id: 30 },
//         { text: 'Literary Fiction', id: 31 },
//         { text: 'Military/Espionage', id: 32 },
//         { text: 'Multicultural', id: 33 },
//         { text: 'Mystery', next: 7, id: 34 },
//         { text: 'Offbeat/Quirky', id: 35 },
//         { text: 'Romance', next: 9, id: 36 },
//         { text: 'Religious/Inspirational', id: 37 },
//         { text: 'Science Fiction', id: 38 },
//         { text: 'Speculative', id: 39 },
//         { text: 'Thrillers/Suspense', id: 40 },
//         { text: 'Upmarket', id: 41 },
//         { text: 'Western', id: 42 },
//         { text: 'Women\'s Fiction', id: 43 },
//     ],
//     4: [ // new adult & ya genres
//         { text: 'Christian', id: 44 },
//         { text: 'Contemporary', id: 20 },
//         { text: 'Fantasy', next: 6, id: 24 },
//         { text: 'Historical', id: 27 },
//         { text: 'Horror', id: 28 },
//         { text: 'Humor', id: 45 },
//         { text: 'LGBTQ+', id: 30 },
//         { text: 'Literary', id: 46 },
//         { text: 'Mystery', next: 7, id: 34 },
//         { text: 'Paranormal', id: 47 },
//         { text: 'Paranormal Romance', id: 48 },
//         { text: 'Romance', next: 9, id: 36 },
//         { text: 'Science Fiction', id: 38 },
//         { text: 'Speculative', id: 39 },
//         { text: 'Thriller/Suspense', id: 49 },
//     ],
//     5: [ // mg genres
//         { text: 'Adventure', id: 50 },
//         { text: 'Christian', id: 44 },
//         { text: 'Contemporary', id: 20 },
//         { text: 'Fantasy', next: 6, id: 24 },
//         { text: 'Historical', id: 27 },
//         { text: 'Horror', id: 28 },
//         { text: 'Humor', id: 45 },
//         { text: 'Literary', id: 46 },
//         { text: 'Mystery', next: 7, id: 34 },
//         { text: 'Science Fiction', id: 38 },
//     ],
//     6: [ // fantasy sub genres 
//         { text: 'Contemporary/Urban Fantasy', id: 51 },
//         { text: 'Dark Fantasy', id: 52 },
//         { text: 'High/Epic Fantasy', id: 53 },
//         { text: 'Historical Fantasy', id: 54 },
//         { text: 'Magical Realism', id: 55 },
//         { text: 'Paranormal Fantasy', id: 56 },
//         { text: 'Steampunk Fantasy', id: 57 },
//     ],
//     7: [ // mystery sub genres 
//         { text: 'Cozy', id: 58 },
//         { text: 'Historical', id: 27 },       
//     ],
//     8: [// picture book sub genres
//         { text: 'Picture Book', id: 6 },
//         { text: 'Author', id: 59 },
//         { text: 'Author/Illustrator', id: 60 },
//         { text: 'Illustrator', id: 61 },
//     ],
//     9: [ // romance sub genres 
//         { text: 'Amish Romance', id: 62 },
//         { text: 'Romantic Comedy', id: 63 },   
//         { text: 'Contemporary Romance', id: 64 },
//         { text: 'Fantasy Romance', id: 65 },
//         { text: 'Gothic Romance', id: 66 },
//         { text: 'Historical Romance', id: 67 },
//         { text: 'Inspirational Romance', id: 68 },
//         { text: 'LGBTQ+ Romance', id: 69 },
//         { text: 'Multicultural Romance', id: 70 },
//         { text: 'Paranormal Romance', id: 47 },
//         { text: 'Regency Romance', id: 71 },
//         { text: 'Southern Romance', id: 72 },
//         { text: 'Sweet Romance', id: 73 },       
//         { text: 'Romantic Suspense', id: 74 },  
//         { text: 'Western Romance', id: 75 },
//     ],
//     10: [ // Non Fiction Genres
//         { text: 'Arts & Entertainment', next: 11, id: 76 },
//         { text: 'Biography & Memoir', next: 12, id: 77 },
//         { text: 'Business & Finance', id: 78 },
//         { text: 'Food & Lifestyle', next: 13, id: 79 },
//         { text: 'Home & Garden', next: 14, id: 80 },
//         { text: 'Current Events & Social Issues', next: 15, id: 81 },
//         { text: 'Health & Wellness', next: 16, id: 82 },
//         { text: 'History & Military', next: 17, id: 83 },
//         { text: 'Hobbies & Interests', next: 18, id: 84 },
//         { text: 'Reference & Education', next: 19, id: 85 },
//         { text: 'Relationships & Personal Growth', next: 20, id: 86 },
//         { text: 'Religion & Spirituality', id: 87 },
//         { text: 'Science & Technology', id: 88 },
//         { text: 'Social Sciences', next: 21, id: 89 },
//         { text: 'True Crime & Adventure', id: 90 },
//     ],
//     11: [
//         { text: 'Arts & Entertainment General', id: 91 },
//         { text: 'Art/Photography', id: 92 },
//     ],
//     12: [
//         { text: 'Biography', id: 93 },
//         { text: 'Memoir', id: 94 },
//     ],
//     13: [
//         { text: 'Cookbook', id: 95 },
//         { text: 'Food/Lifestyle', id: 96 },
//     ],
//     14: [
//         { text: 'Decorating/Design', id: 97 },
//         { text: 'Gardening', id: 98 },
//     ],
//     15: [
//         { text: 'Cultural/Social Issues', id: 99 },
//         { text: 'Current Affairs/Politics', id: 100 },
//     ],
//     16: [
//         { text: 'Health/Fitness', id: 101 },
//         { text: 'Psychology', id: 102 },
//     ],
//     17: [    
//         { text: 'History', id: 103 },
//         { text: 'Military', id: 104 },
//     ],
//     18: [
//         { text: 'How To', id: 105 },
//         { text: 'Humor/Gift Book', id: 106 },
//         { text: 'Pop Culture', id: 107 },
//         { text: 'Pets', id: 108 },
//         { text: 'Sports', id: 109 },
//         { text: 'Travel', id: 110 },
//     ],
//     19: [ 
//         { text: 'General Non-Fiction', id: 111 },
//         { text: 'Juvenile/Graphic', id: 112 },
//         { text: 'Reference', id: 113 },
//     ],
//     20: [
//         { text: 'Relationship/Dating', id: 114 },
//         { text: 'Self-Help', id: 115 },
//     ],
//     21: [
//         { text: 'LGBTQ+', id: 30 },
//         { text: 'Multicultural', id: 33 },
//         { text: 'Nature/Ecology', id: 116 },
//         { text: 'Parenting', id: 117 },
//         { text: 'Women\'s Issues', id: 118 },
//     ],
// };

// export default PubTree;
